name: 'stock_analytics'
version: '1.0.0'
config-version: 2
profile: 'default'
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  stock_analytics:
   # +schema: analytics
    input:
      +materialized: view     
    output:
      +materialized: table
