version: 2

models:
  - name: stg_prices
    description: Staging view for stock prices
    columns:
      - name: SYMBOL
        tests:
          - not_null
      - name: DT
        tests:
          - not_null

  - name: daily_change
    description: Daily stock price changes and direction
    columns:
      - name: SYMBOL
        tests:
          - not_null
      - name: DT
        tests:
          - not_null
      - name: direction
        tests:
          - accepted_values:
              values: ['UP', 'DOWN', 'FLAT']

  - name: moving_avg
    description: 7-day and 30-day moving averages
    columns:
      - name: SYMBOL
        tests:
          - not_null
      - name: DT
        tests:
          - not_null
      - name: trend_signal
        tests:
          - accepted_values:
              values: ['ABOVE_MA', 'BELOW_MA']
